[package]
name = "rat"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
screenshots = "0.8.10"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "*"
futures-util = "*"
url = "2.5.4"
gethostname = "1.0.1"
